pip install bit
pip install requests
pip install mnemonic
pip install bip32utils
pip install base58
pip install hdwallet
pip install simplebloomfilter
pip install bitarray==1.9.2
pip install lxml
pip install rich
